### ISSUE TITLE
Asset Visuals Page/Tab UI

### ISSUE THREAD

**Issue by Conalyst** [Conalyst/ProjectDashboard#6]
Create Asset Visuals page. Remember to make the graphs clickable, pay attention to which elements have hover and drop-down.

**Comment by Lunettes0910** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorporating dashboard sub-pages into main page components](https://trello.com/c/PCheeGhT/6-incorporating-dashboard-sub-pages-into-main-page-components)

**Comment by Conalyst** [comment]
Completed Visuals TAB, next step is to add Asset graphs to fill page
