### ISSUE TITLE
Add graphs to Visual Pages UI

### ISSUE THREAD

**Issue by Conalyst** [Conalyst/ProjectDashboard#8]
- Needs to be bar graph, lines going vertical
- Needs to be bar graph, lines going horizontal

Possibility of making the graphs clickable. E.g., click on a bar that says Medium, will then will highlight all medium scores.
- Needs to be connected to the *Filter* feature

**Comment by Lunettes0910** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorporating dashboard sub-pages into main page components](https://trello.com/c/PCheeGhT/6-incorporating-dashboard-sub-pages-into-main-page-components)

**Comment by Conalyst** [comment]
done
